### ISSUE TITLE
any idea on how can we calculate the intrinsic in Gazebo

### ISSUE THREAD

**Issue by ibra860** [ra13o/camera_lidar_fusion#2]
#Camera Intrinsic Parameters
    fx = 476.53698  # focal_length in x
    fy = 476.57264  # focal_length in y
    cx = 399.86767  # center in x
    cy = 400.15544  # center in y

in Gazebo I will add camera, but how to get this data?

**Comment by ibra860** [comment]
Update: 
if you are publishing from gazebo, you may find topic /<what_ever>/camera_info
it will contain a msg like this
```
---
header:
  stamp:
    sec: 1016
    nanosec: 755000000
  frame_id: your_frame/front_cam_link_optical
height: 1080
width: 1920
distortion_model: plumb_bob
d:
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
k:
- 554.5091528011569
- 0.0
- 960.5
- 0.0
- 554.5091528011569
- 540.5
- 0.0
- 0.0
- 1.0
r:
- 1.0
- 0.0
- 0.0
- 0.0
- 1.0
- 0.0
- 0.0
- 0.0
- 1.0
p:
- 554.5091528011569
- 0.0
- 960.5
- -38.81564069608099
- 0.0
- 554.5091528011569
- 540.5
- 0.0
- 0.0
- 0.0
- 1.0
- 0.0
binning_x: 0
binning_y: 0
roi:
  x_offset: 0
  y_offset: 0
  height: 0
  width: 0
  do_rectify: false
```
